name: Reusable Deploy
on: 
    workflow_call:
      inputs:
        artifact-name:
            description: The name of the deployable artifact files
            required: false
            default: dist
            type: string
      secrets:
        some-secret:
            required: false
      outputs:
        result: 
            description: The output of deployment opration
            value: ${{jobs.deploy.outputs.outcome}}
jobs:
    deploy:
        outputs:
            outcome: ${{steps.set-set-results.outputs.step-result}}
        runs-on: ubuntu-latest
        steps:
            - name: Get artifacts
              uses: actions/download-artifact@v3
              with:
                name: ${{ inputs.artifact-name}}
            - name: List files
              run: ls
            - name: Output info
              run: echo "Deploying ${{secrets.some-secret}}"
            - name: Set result output
              id: set-results
              run: echo "step-result=success" >> $GITHUB_OUTPUT

